config/routes.rb
MakeSandwich::Application.routes.draw do
  devise_for :users
  resources :users
  resources :condiments
  resources :ingredients
  resources :containers

  match 'orders/thank_you' => 'orders#thank_you'
  resources :orders

  match 'sandwiches/:id/copy' => 'sandwiches#copy_sandwich'
  match 'sandwiches/select_theme' => 'sandwiches#select_theme'
  resources :sandwiches

  root :to => 'orders#welcome'

end

app/models/sandwich.rb
class Sandwich < ActiveRecord::Base
  attr_accessible :containers, :ingredients, :order_id

  has_many :sandwich_containers
  has_many :containers, :through => :sandwich_containers
  has_many :sandwich_ingredients
  has_many :ingredients, :through => :sandwich_ingredients
  belongs_to :order

  validate :length_of_containers
  validates :order_id, :presence => true

  def length_of_containers
    if self.containers.length != 1
      errors.add(:containers, "must be 1 and only 1 container for a sandwich")
    end
  end

  before_save :assure_unique_ingredients

  # sorry - no double cheese :)
  def assure_unique_ingredients
    self.ingredients.uniq!
  end

  def container
    containers.first
  end

  def container=(value)
    containers.pop
    containers << value
  end

  def self.update_one(options = {})
    sandwich = find options[:id]
    sandwich.container = Container.find(options[:container]) if options[:container].present?
    sandwich.ingredients = [Ingredient.find(options[:ingredients])].flatten if options[:ingredients].present?
    sandwich
  end

  def self.build_one(options = {})
    sandwich = new
    sandwich.order_id = options[:order_id] if options[:order_id].present?
    sandwich.container = Container.find(options[:container]) if options[:container].present?
    sandwich.ingredients = [Ingredient.find(options[:ingredients])].flatten if options[:ingredients].present?
    sandwich
  end

  def self.copy(id)
    sandwich = find(id)
    new_sandwich = new
    new_sandwich.theme = sandwich.theme
    new_sandwich.container = sandwich.container
    new_sandwich.ingredients = sandwich.ingredients
    new_sandwich
  end

  # 3 types of sandwiches as starting points
  def self.meaty
    sandwich = new
    sandwich.theme = "Meaty"
    sandwich.container = Container.last
    sandwich.ingredients = [
        Meat.meaty, Cheese.first
    ].flatten
    sandwich
  end

  def self.veggie
    sandwich = new
    sandwich.theme = "Veggie"
    sandwich.container = Container.last
    sandwich.ingredients = [
        Meat.veggie, Cheese.last, Vegetable.all
    ].flatten
    sandwich
  end

  def self.vegan
    sandwich = new
    sandwich.theme = "Vegan"
    sandwich.container = Container.first
    sandwich.ingredients = [
        Vegetable.all
    ].flatten
    sandwich
  end

  def self.examples
    ["Meaty", "Veggie", "Vegan"]
  end

  def self.themed(options = {})
    logger.debug "themed options: #{options.inspect}"
    sandwich =
        case options[:theme]
          when 'Meaty'
            meaty
          when 'Veggie'
            veggie
          when 'Vegan'
            vegan
          else
            new
        end
    sandwich.order_id = options[:order_id]
    sandwich
  end

end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  before_filter :set_user
  before_filter :get_order

  def get_order
    @order = Order.find(session[:order_id]) if session[:order_id]
    logger.debug "current order session: #{@order.id}" if @order
  end

  # GET /sandwiches
  # GET /sandwiches.json
  def index
    @sandwiches = Sandwich.where(order_id: @order.id) if @order
    @sandwiches ||= Sandwich.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sandwiches }
    end
  end

  # GET /sandwiches/1
  # GET /sandwiches/1.json
  def show
    @sandwich = Sandwich.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sandwich }
    end
  end

  def edit_session
    params.merge!(order_id: @order.id)
    @sandwich_examples = Sandwich.examples
    @containers = Container.order(:name)
    @ingredients = Ingredient.all
    @meats = @ingredients.select{|i| i.class == Meat}.sort{|a,b| a.name <=> b.name}
    @veggies = @ingredients.select{|i| i.class == Vegetable}.sort{|a,b| a.name <=> b.name}
    @cheeses = @ingredients.select{|i| i.class == Cheese}.sort{|a,b| a.name <=> b.name}
    @condiments = @ingredients.select{|i| i.class == Condiment}.sort{|a,b| a.name <=> b.name}
  end

  def select_theme
    @sandwich = Sandwich.themed(params)
    logger.debug "current sandwich: #{@sandwich.ingredients.inspect} on #{@sandwich.container.name}"
    edit_session
  end

  def copy_sandwich
    # new order started
    @order = if session[:order_id]
      Order.find(session[:order_id])
    else
      order = Order.create(user_id: @user.id)
      session[:order_id] = order.id
      order
    end

    @sandwich = Sandwich.copy(params[:id])
    @sandwich.order_id = @order.id
    logger.debug "current sandwich: #{@sandwich.ingredients.inspect} on #{@sandwich.container.name}"
    edit_session
    render :new
  end

  # GET /sandwiches/new
  # GET /sandwiches/new.json
  def new
    @sandwich = Sandwich.new
    edit_session

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sandwich }
    end
  end

  # GET /sandwiches/1/edit
  def edit
    @sandwich = Sandwich.find(params[:id])
    edit_session
  end

  # POST /sandwiches
  # POST /sandwiches.json
  def create
    params.merge!(order_id: @order.id)
    @sandwich = Sandwich.build_one(params)

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to :action => :index, notice: 'Sandwich was successfully created.' }
        format.json { render json: @sandwich, status: :created, location: @sandwich }
      else
        edit_session
        format.html { render action: "new" }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sandwiches/1
  # PUT /sandwiches/1.json
  def update
    @sandwich = Sandwich.update_one(params)

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sandwiches/1
  # DELETE /sandwiches/1.json
  def destroy
    @sandwich = Sandwich.find(params[:id])
    @sandwich.destroy

    respond_to do |format|
      format.html { redirect_to sandwiches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper

  def container_selected?(id)
    container_id = params[:container]
    container_id ||= @sandwich.container.id if @sandwich.container
    container_id.to_i == id
  end

  def ingredient_included?(id)
    ingredient_ids = params[:ingredients]
    ingredient_ids ||= @sandwich.ingredients.map{|i| i.id.to_s if i}.compact
    ingredient_ids.include?(id.to_s)
  end

  def ingredient_id(id)
    "i#{id}"
  end

  def no_sandwiches?
    @sandwiches.blank? ? true : @sandwiches.length == 0
  end

end

app/views/sandwiches/_form.html.erb
<div id="sandwich_form">
<%= form_for(@sandwich) do |f| %>
  <% if @sandwich.errors.any? %>
    <div class="control-group error">
      <h2><%= pluralize(@sandwich.errors.count, "error") %> prohibited this sandwich from being saved:</h2>

      <ul>
      <% @sandwich.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="fluid-row">
      <label for="theme">Choose a Sandwich Theme for some preset values:</label>
      <%= select_tag 'theme', options_for_select([''] + [@sandwich_examples].flatten, @sandwich.theme),
                     :'data-remote' => true,
                     :'data-url' => sandwiches_select_theme_path %>
      <% image_display = "display: none;" if @sandwich.theme %>
      <div id="theme_image" style="<%= image_display %>"></div>
    </div><br/>

    <div class="fluid-row">
      <label for="containers">Containers:</label>
      <% @containers.each do |c| %>
          <label class="radio">
          <%= c.name %>
          <%= radio_button_tag :container, c.id, container_selected?(c.id) %>
          </label>
      <% end %>
    </div><br/>

    <div class="fluid-row">
    Ingredients<br/>
    <label class="radio"><%= check_box_tag "all_tag", nil, nil, onclick: "selectAll()" %>
    Select All</label>
    <label class="radio"><%= check_box_tag "none_tag", nil, nil, onclick: "selectNone()" %>
    Select None</label>
    </div><br/>

    <div id="ingredients">
    <div class="fluid-row">
      <label for="ingredients">Meats:</label>
      <% @meats.each do |c| %>
          <label class="radio">
          <%= check_box_tag "ingredients[]", c.id, ingredient_included?(c.id), :id => ingredient_id(c.id) %>
            <%= c.name %>
          </label>
      <% end %>
    </div><br/>

    <div class="fluid-row">
      <label for="ingredients">Veggies:</label>
      <% @veggies.each do |c| %>
          <label class="radio">
          <%= check_box_tag "ingredients[]", c.id, ingredient_included?(c.id), :id => ingredient_id(c.id) %>
            <%= c.name %>
          </label>
      <% end %>
    </div><br/>

    <div class="fluid-row">
      <label for="ingredients">Cheeses:</label>
      <% @cheeses.each do |c| %>
          <label class="radio">
          <%= check_box_tag "ingredients[]", c.id, ingredient_included?(c.id), :id => ingredient_id(c.id) %>
            <%= c.name %>
          </label>
      <% end %>
    </div><br/>

    <div class="fluid-row">
      <label for="ingredients">Condiments:</label>
      <% @condiments.each do |c| %>
          <label class="radio">
          <%= check_box_tag "ingredients[]", c.id, ingredient_included?(c.id), :id => ingredient_id(c.id) %>
            <%= c.name %>
          </label>
      <% end %>
    </div><br/>
    </div>

    <%= f.submit 'Submit' %>
  </div>
<% end %>
</div>

app/views/sandwiches/_list.html.erb
<h1>Listing sandwiches for your Order</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sandwiches.each_with_index do |sandwich, idx| %>
  <tr>
    <td><%= idx + 1 %>. <%= sandwich.ingredients.present? ?
                                    sandwich.ingredients.collect_names : "nothing" %> in a
      <%= sandwich.container.name if sandwich.container %>
    </td>
    <td><%= link_to '', edit_sandwich_path(sandwich), class: "icon-pencil" %></td>
    <td><%= link_to '', sandwich, class: "icon-trash", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br/>

app/views/sandwiches/_past.html.erb
<h1>Listing sandwiches for your Past Order</h1>

<table>
  <tr>
    <th></th>
    <th></th>
  </tr>

<% @sandwiches.each_with_index do |sandwich, idx| %>
  <tr>
    <td><%= idx + 1 %>. <%= sandwich.ingredients.present? ?
                                    sandwich.ingredients.collect_names : "nothing" %> in a
      <%= sandwich.container.name if sandwich.container %>
    </td>
    <td><%= link_to '', sandwich_path(sandwich) + '/copy', id: 'copy_sandwich',
                    class: "icon-retweet" %></td>
  </tr>
<% end %>
</table>

<br/>

app/views/sandwiches/edit.html.erb
<h1>Editing sandwich</h1>

<%= render 'form' %>

<%= link_to 'Show', @sandwich %> |
<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/index.html.erb
<%= render :partial => 'list' %>

<%= link_to 'Add a Sandwich', new_sandwich_path %><br/>
<br/>
<%= button_to 'Submit Order', orders_thank_you_path, :disabled => no_sandwiches? %>

app/views/sandwiches/new.html.erb
<h1>New sandwich</h1>

<%= render 'form' %>

<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/select_theme.js.erb
$('#sandwich_form').replaceWith("<%= escape_javascript(render :partial => "form") %>");

app/views/sandwiches/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sandwich_path(@sandwich) %> |
<%= link_to 'Back', sandwiches_path %>