config/routes.rb
MakeSandwich::Application.routes.draw do
  devise_for :users
  resources :users
  resources :condiments
  resources :ingredients
  resources :containers

  match 'orders/thank_you' => 'orders#thank_you'
  resources :orders

  match 'sandwiches/:id/copy' => 'sandwiches#copy_sandwich'
  match 'sandwiches/select_theme' => 'sandwiches#select_theme'
  resources :sandwiches

  root :to => 'orders#welcome'

end

app/models/container.rb
class Container < ActiveRecord::Base
  attr_accessible :name
  has_many :sandwich_containers
  has_many :sandwiches, :through => :sandwich_containers

  validates :name, :presence => true, :uniqueness => true
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @containers }
    end
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
    @container = Container.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @container }
    end
  end

  # GET /containers/new
  # GET /containers/new.json
  def new
    @container = Container.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @container }
    end
  end

  # GET /containers/1/edit
  def edit
    @container = Container.find(params[:id])
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(params[:container])

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render json: @container, status: :created, location: @container }
      else
        format.html { render action: "new" }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /containers/1
  # PUT /containers/1.json
  def update
    @container = Container.find(params[:id])

    respond_to do |format|
      if @container.update_attributes(params[:container])
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container = Container.find(params[:id])
    @container.destroy

    respond_to do |format|
      format.html { redirect_to containers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<h1>Listing containers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @containers.each do |container| %>
  <tr>
    <td><%= container.name %></td>
    <td><%= link_to '', container, class: "icon-search" %></td>
    <td><%= link_to '', edit_container_path(container), class: "icon-pencil" %></td>
    <td><%= link_to '', container, class: "icon-trash", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @container.name %>
</p>


<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>